CREATE DATABASE QLNV
GO

USE QLNV

CREATE TABLE ACCOUNT
(
	USERNAME varchar(100) NOT NULL PRIMARY KEY,
	PASS varchar(50) NOT NULL
)
INSERT INTO ACCOUNT(USERNAME,PASS)
VALUES ('dat1','1') 
GO
CREATE PROCEDURE USP_Login
@userName nvarchar(100), @passWord nvarchar(100) 
AS
BEGIN 
	SELECT * FROM dbo.Account WHERE USERNAME = @userName AND PASS = @passWord
END
GO
SELECT * FROM ACCOUNT
GO

CREATE TABLE NHANVIEN
(
	STT int IDENTITY NOT NULL,
	MANV nvarchar(10) NOT NULL PRIMARY KEY,
	HOTEN nvarchar(50) NOT NULL,
	GIOITINH nvarchar(3),
	NGSINH smalldatetime,
	CHUCVU nvarchar(20) NOT NULL
) 
GO
DROP TABLE NHANVIEN
CREATE TABLE MONAN
(
	TENMON nvarchar(10) NOT NULL PRIMARY KEY,
	LOAIMONAN nvarchar(50) NOT NULL,
	SOLUONG tinyint NOT NULL,
	GIA money
)
GO
drop table MONAN
CREATE TABLE GOIMON
(
	TENMON varchar(10) NOT NULL,

)
CREATE TABLE HOADON
(
	SOHD INT IDENTITY NOT NULL PRIMARY KEY,
	THOIGIANLAP smalldatetime,
	MASOBAN INT NOT NULL,
	TONGTIEN FLOAT
)
GO
SET DATEFORMAT DMY
INSERT INTO NHANVIEN(MANV,HOTEN,GIOITINH,NGSINH,CHUCVU) VALUES ('A02',N'Nguyễn Tiến Đạt','Nam','31/12/2001',N'Phục vụ')
SELECT *FROM NHANVIEN

UPDATE NHANVIEN SET HOTEN = N'NGUYỄN VĂN D' WHERE MANV ='A05'
DELETE FROM NHANVIEN WHERE MANV = 'A03'